Bu veri seti, tümörlerini aldırmak için ameliyat olan bir grup meme kanseri hastasından oluşmaktadır. Veri kümesi aşağıdaki değişkenlerden oluşur:

#### Veri İçeriği
Patient_ID: bir hastanın benzersiz tanımlayıcı kimliği

Age: tanı yaşı (Yıl)

Geder: Male(Erkek)  Female(Kadın)

Protein1, Protein2, Protein3, Protein4: ekspresyon seviyeleri (tanımsız birimler)

Tumour_Stage(Tümör_Evresi): I, II, III

Histology: İnfiltratif Duktal Karsinom, İnfiltratif Lobüler Karsinom, Müsinöz Karsinom

ER durumu: Olumlu/Negatif

PR durumu: Olumlu/Negatif

HER2 durumu: Pozitif/Negatif

Surgery_type(Cerrahi_tipi): Lumpektomi, Basit Mastektomi, Modifiye Radikal Mastektomi, Diğer

Date_of_Surgery: Ameliyatın gerçekleştirildiği tarih (GG-MON-YY olarak)

Date_of_Last_Visit: Son ziyaret tarihi (GG-MON-YY olarak) [hastanın ameliyattan sonra tekrar ziyaret etmemesi durumunda boş olabilir]

Patient_Status: Hayatta/Ölü [ameliyattan sonra hastanın tekrar ziyaret etmemesi ve hastanın hayatta olup olmadığına dair bilgi olmaması durumunda boş olabilir].

### - Yaşa göre  meme kanser olma riski

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('BRCA.csv')
df.head()

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive
1,TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
2,TCGA-A8-A079,69.0,FEMALE,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,Alive
3,TCGA-D8-A1XR,56.0,FEMALE,0.345090,-0.21147,-0.19304,0.124270,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,Alive
4,TCGA-BH-A0BF,56.0,FEMALE,0.221550,1.90680,0.52045,-0.311990,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,Dead

In [3]:
df.tail()

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- tail() metodu ile sona bakıldığında nan değerlerin olduğu görünmektedir.

In [5]:
#Nan değerler bakmak için
df.isnull().sum()

Patient_ID             7
Age                    7
Gender                 7
Protein1               7
Protein2               7
Protein3               7
Protein4               7
Tumour_Stage           7
Histology              7
ER status              7
PR status              7
HER2 status            7
Surgery_type           7
Date_of_Surgery        7
Date_of_Last_Visit    24
Patient_Status        20
dtype: int64

In [6]:
df.shape

(341, 16)

In [7]:
df['Patient_Status'].value_counts()

Patient_Status
Alive    255
Dead      66
Name: count, dtype: int64